apiVersion: v1
data:
  logback.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE xml>\n<configuration scan=\"true\" scanPeriod=\"30 seconds\" >\n\t<appender name=\"STDOUT\" class=\"ch.qos.logback.core.ConsoleAppender\">\n        <encoder class=\"net.logstash.logback.encoder.LogstashEncoder\"/>\n    </appender>\n\n\t<root level=\"info\">\n\t\t<appender-ref ref=\"STDOUT\" />\n\t</root>\n</configuration>\n"
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name:  {{ .Values.app.name}}-logback-config
