apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: <replaceme>
  namespace: argocd
spec:
  destination:
    namespace: <replaceme>
    server: https://kubernetes.default.svc
  project: <replaceme>
  source:
    path: dev
    repoURL: git@dgsiaf-gitlab.mecon.ar:openshift/okd4/cicd/pipeline-workflow-config-charts.git
    targetRevision: <replaceme>
    helm:
      parameters:
        - name: app.name
          value: <replaceme>
        - name: build.suscribers
          value: <replaceme>
        - name: mail.recipients
          value: <replaceme>
        - name: team.members
          value: <replaceme>
  syncPolicy:
    automated:
      prune: true
