{{- if .Values.liquibase.enabled }}
apiVersion: v1
data:
  liquibase.database.user: {{ .Values.liquibase.databaseUser}}
  liquibase.database.password: {{ .Values.liquibase.databasePassword}}
kind: Secret
metadata:
  name: {{ .Values.app.name}}-liquibase-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
{{- end }}  